/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_GPIO */

#ifndef _Included_com_example_demo_GPIO
#define _Included_com_example_demo_GPIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_GPIO
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_GPIO_setup
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_GPIO
 * Method:    on
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_GPIO_on
  (JNIEnv *, jobject);

/*
 * Class:     com_example_demo_GPIO
 * Method:    off
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_GPIO_off
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
